crate/crate-benchmarks

- src/test/java/io/crate/benchmark/PartitionedBulkInsertBenchmark.java
would make it possible to run the test on machines with slow
io write speed
> increase bulk insert timeout for partitioned bulk insert test

- rerun-bench.sh
re-runs stresstests with the nightly builds that are available on the public cdn
> added shell script that runs nightly build history

- rerun-bench.sh
e.g.
single argument
```bash
./rerun-bench.sh crate-0.55.0-201602140301-810e333.tar.gz
```
multiple arguments (comma separated)
```bash
./rerun-bench.sh crate-0.55.0-201602140301-810e333.tar.gz, crate-0.55.0-201601210301-6d30328.tar.gz 
```
> added support for nightly build argument list

- build.gradle
In order to workaround an issue in the CrateClient from current master.
Besides, for stress tests we don't want to execute assertions anyway.
> Don't enable assertions

- src/test/java/io/crate/benchmark/PartitionedTableBenchmark.java
ensures green state of partitioned table to be sure that all shards are
allocated.
> fix: ensure that shards are allocated

- src/test/java/io/crate/benchmark/PartitionedTableBenchmark.java
this creates only 500 shards instead of 2500 (default)
> decrease num_shards in PartitionedTableBenchmark

- api/schema.sql
- api/setup.py
- api/src/crate/benchapi/application.py
- api/src/crate/benchapi/scripts.py
this script needs to be run after the benchmark run in order to update
the version_info column with the commit date of the crate version
this is required for the benchmark api to order by timestamp
@bogensberger can you take a look please
> added script that fetches commit date from github

- api/src/crate/benchapi/application.py
since the connection is an app global, it must not be closed when the resource is deleted
> do not close connection when resource is deleted

- py/README.rst
- py/compare.py
Sample usage:
./compare.py --v1 1.0.1 --v2 1.0.2 --spec fast/queries.toml
```
V1: 1.0.1-22739b23820d93bdcf70878cf80342485b33c3c4
V2: 1.0.2-8d1ce516bc8d6fb0dad6231499ebd623eb5208e8
('select * from uservisits limit 10', 1)
0.50% mean difference. Likely NOT significant
V1  →     V2
mean:    1.300 →   1.294
stdev:   1.391 →   1.529
max:    41.318 →  43.823
min:     0.798 →   0.766
('select extract(day from "visitDate"), count(*) from uservisits group by 1 order by 2 desc limit 20', 1)
4.82% mean difference. Likely NOT significant
V1  →     V2
mean:    1.673 →   1.755
stdev:   1.729 →   1.740
max:    38.352 →  36.274
min:     1.153 →   1.132
```
> Add script to run a spec against 2 versions

- py/specs/joins.toml
Increases the iterations from 50 to 2560 because with only 50 iterations
the result against the same CrateDB version deviated between by up to
15%
> Increase iterations for ordered cross join

- py/specs/select/simple_subquery.toml
This requires functionality that is in the `simple-subquery` branch in the
crate project, so don't merge yet.
First query:
```
Runtime (in ms):
mean:    24.132 ± 0.181
min/max: 9.362 → 70.624
Percentile:
50:   24.887 ± 4.129 (stdev)
95:   27.873
99.9: 63.995
```
Second query: (this should get a lot faster once we add the fetch-propagation optimization)
```
Runtime (in ms):
mean:    1287.632 ± 25.463
min/max: 1137.688 → 1486.777
Percentile:
50:   1290.236 ± 91.861 (stdev)
95:   1434.237
99.9: 1486.777
```
> Add benchmarks for simple subquery

- py/specs/joins.toml
The query was really slow (> 1800sec) because the pre-join ORDER BY
optimization can't be applied and sorting 100k*100k rows is slow.
> Change slow join query into one that is a lot faster

- py/specs/select/disabled_doc_values.toml
- py/specs/sql/uservisits_no_doc_values.sql
- py/tracks/latest.toml
groupings, aggregates and ordering on columns with disabled doc_values
uses a source lookup. this benchmarks are intended to be compared to the
equivalent benchmarks with enabled doc_values to see the performance
differences
> adds benchmarks for disabled doc_values/column store

- py/specs/joins.toml
The benchmark
select * from articles inner join colors on articles.id = colors.id
where colors.id = -1
depends a lot on the number of segments because one side doesn't match
at all. Our current NL implementation still retries to iterate over the
right side for each left row and if each segment contains no matching
row the cost of setting up the doc-iteration per segment is
proportionally high.
We should optimize this eventually in CrateDB, but this here is to avoid
having the benchmarks fluctuate so much, to reduce false positive
regression notifications.
> Stabilize join benchmark by running optimize table

- py/find_regressions.py
- py/specs/in_subquery.toml
- py/specs/joins.toml
Increased the error quotient from 10% to 15% due to high query runtime
fluctuations on a lot of queries on the benchmark servers.
Additionally it is necessary to define certain queries as "unstable"
since their error quotient is most of the time higher than 15%.
> stabilized performance regression in nightly benchmarks

- py/find_regressions.py
Given the large fluctuation of the benchmarks comparing only the last
two results results in a large number of false positive alerts.
Furthermore it has the "boiling frog" problem in that we don't detect
slow regressions over time if we constantly ignore 10%+ differences.
This changes the approach: Now it looks at the last 20 results in
compares the latest with the *worst* of the previous 19 results. This should reduce the change of false positive alerts and at the same time improve the chance of detecting slow regressions.
> Change find_regressions to look at more data and use a breakout approach

- py/tracks/default.toml
Has been removed in CrateDB 3.0
> Remove `indices.store.throttle.max_bytes_per_sec`

- query_tests/generate_rnd_queries.py
Some functions (ceil, round etc) can return an integer. Previously we made
the compare value be a random value of the same type as the column used
as argument for the function call. These functions would yield an integer
which we attempted to compare with a random float literal for eg.
We then attempted to convert the literal to an integer, which could be out
of range for the integer type.
This commit changes the compare value to be of type byte for these functions.
> The compare value doesn't exceed the range of the return type of math functions.

- query_tests/generate_rnd_queries.py
The change in cr8 https://github.com/mfussenegger/cr8/commit/3ef2040dd49eeeee4937f2e35d368e1e15651313 broke the value generation for timestamps, leading to queries like this:
SELECT count(*) FROM \"benchmarks\".\"query_tests\" WHERE 2016-08-20
23:16:44 >= ANY (\"atimestamp\") AND \"slong\" <= -3771834702135012260
AND \"stimestamp\" != 2017-02-19 23:43:01;
> rnd_queries: Use unix_time for timestamp value generation

- specs/group_by.toml
Running them sequentially is not ideal:
- It's more artificial: Having an idle node where a single query is
run sequentially is rather unrealistic
- Since there is lower GC pressure the chance to observe a full GC is
lower, this can lead to flaky results. Some runs with a full GC happening
during the measurement and some without.
This also removes `max` and `arbitrary` aggregations. We're not so much
interested in the performance of different aggregation functions, but
rather in the behaviour of the whole pipeline.
We could do targeted JMH benchmarks to compare aggregation functions.
> Change GROUP BY queries to run with concurrency

- compare.py
- requirements.txt
So spec files using gzipped files can be used with ./compare.py
> Update cr8 to 0.13.0

- README.rst
- compare_measures.py
- compare_run.py
- compare.py - prints the diff of the measures read from 2 files
- compare_run.py - does the same thing as compare.py did before
The former will be useful to compare the results from measures taken
using a different "runner". E.g. by running a spec file directly against
an existing cluster.
> Split compare.py into 2 scripts

- specs/group_by_cardinality_long.toml
To make it more suitable to run comparisons on clusters
> Increase used shards in group_by_cardinality_long

- specs/group_by.toml
We've multiple ones with `group by cCode` using different aggregation
functions. To compare aggregation function performance we'd be better of
with JMH based benchmarks. Having multiple groupings in one query allows
us to see the behavior of slightly different execution paths in the
engine.
> Change one group by query case to use multiple columns

- specs/sql/generated_columns.sql
Broke due to a missing column and new `static` column_policy default.
> Fix benchmark for generated_columns

- compare_run.py
Using options like `--env-v2 CRATE_JAVA_OPTS="-XX:InitiatingHeapOccupancyPercent=75"`
didn't work.
> Allow passing env options containing `=` to compare_run

- tracks/default.toml
This raises it from 60% to 80%, due to the recent accounting
improvements made in CrateDB, some of the queries started hitting the
threshold of 60%.
We know that the queries should work as we were able to successfully run
them before the circuit breaker improvements, so raising the limit
should be safe for the benchmarks.
> Raise the query circuit breaker limit

- .editorconfig
- JfrOverview.java
- compare_measures.py
- compare_run.py
Example output:
Q: select count(distinct "searchWord") from uservisits group by "cCode"
C: 5
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |      945.619 ±  285.149 |    762.244 |    881.228 |    936.162 |   2187.417 |
|   V2    |      946.812 ±  160.640 |    722.209 |    916.833 |    958.813 |   1720.607 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   0.13%                           +   3.96%
There is a 2.90% probability that the observed difference is not random, and the best estimate of that difference is 0.13%
The test has no statistical significance
System/JVM Metrics (durations in ms, byte-values in MB)
|    YOUNG GC            |       OLD GC           |      HEAP …
> Add metrics extracted from JFR to compare_run

- specs/group_by.toml
Queries: group by a single numeric and mixed keys.
It is done in scope of https://github.com/crate/crate/pull/10481
> Add few queries to the group by spec.

- specs/select/count.toml
Relates to https://github.com/crate/crate/pull/10588
> Extend count benchmarks with aliased table case

- query_tests/generate_rnd_queries.py
Upcoming breaking change in 4.3 that changes the function to a table
function:
UnsupportedFeatureException[Table functions are not allowed in WHERE] occurred using: {"stmt": "SELECT count(*) FROM \"benchmarks\".\"query_tests\" WHERE -21 != ANY (\"abyte\") AND 'sea' != ANY (\"astring\") OR \"sinteger\" >= 1432055804 AND ageo_point IS NULL OR REGEXP_MATCHES(sstring, '(a(.+)z)') = ['exactly'];"}
> Remove regexp_matches from query tests

- specs/any.py
- specs/in_numeric.toml
The query became quite slow with 4.0.0 because of the removal of the
implicit HTTP limit. The query returns ~1516033 records which is quite a
lot.
The original purprose of the query was to benchmark the `duration IN`
clause, not the retrieval of large results, so this adjusts the query to
do a `count(*)` which reduces the overhead of the result set processing.
> Change query in `in_numeric` to use count(*)

- tracks/latest.toml
Some of the spec files in `specs/select/*.toml` shouldn't be included in
the nightly run. (For example the wide_table scenario)
> Declare specs/select/ cases in track file explicitly

- generators/gen-data.py
- generators/gen_specific_distribution.sh
- specs/group_by_distribution_long.toml
- specs/group_by_distribution_string.toml
Relates to https://github.com/crate/crate/issues/11413
Added new data sets (1 million records each) with different distributions, generator and a new spec
Some other distributions are similar to exisiting, like binomial being discrete version of normal (could have actually dropped normal and used binomial but went with normal as it's possible to convert it to int )
tried some others - they are in general either bell-shaped like normal or look like exponential, we can add them of course but this is the minimal list of basic "shapes"
Poisson can be approximated to normal but with small loc it's right skewed - included it as well as it's another possible shape.
Plots generated by 
```
#plt.hist(np.random.normal(loc=0, scale=1e10, size=1000000).astype(long), bins=100) …
```
> add data sets with different distributions and spec for group by

- generators/gen-data.py
Relates to https://github.com/crate/crate/issues/11413
I didn't do shift in the prev PR as I misunderstood statement [constant multiplied by a Poisson random variable is not Poisson](https://math.stackexchange.com/questions/746760/prove-that-a-constant-multiplied-by-a-poisson-random-variable-is-not-poisson)
We can use rule [If X1 and X2 are Poisson random variables with means μ1 and μ2 respectively, then X1 + X2 is a Poisson random variable with mean μ1 + μ2.]( https://en.wikipedia.org/wiki/Relationships_among_probability_distributions#Sum_of_variables) - so we just re-use variable X as many times as we need and get an updated variable which is sum of many poisson variables. 
Essentially, we are multiplying the whole formula by `1e10`, ie. multiplying output vector, whereas …
> update Poisson distribution to get big numbers

- generators/gen-data.py
add encoding, avoid integers numbers being writen as `X.0` because of multiplication by `e10`.
> encoding and avoid e10 in final array as spec cannot handle int

- tracks/default.toml
Relates to https://github.com/crate/crate-alerts/issues/225
Problematic query/concurrency combination is
```
statement = 'select t1."sourceIP" from uservisits_large t1 inner join uservisits_small t2 
on t1."sourceIP" = t2."sourceIP" 
order by t1."sourceIP" limit 1000'
iterations = 20
min_version = '3.0.0'
concurrency = 20
```
I changed `hash_joins` spec locally to contain only one query:
```
[setup]
statement_files = ["../sql/uservisits_large_and_small.sql"]
[[queries]]
statement = 'select t1."sourceIP" from uservisits_large t1 inner join uservisits_small t2 on t1."sourceIP" = t2."sourceIP" order by t1."sourceIP" limit 1000'
iterations = 20
min_version = '3.0.0'
concurrency = 20
[teardown]
statements = ["drop table if exists uservisits_small", "drop table if exists uservisits_large"]
``` …
> increase breaker.query.limit for the public benchmark

- tracks/default.toml
resolves https://github.com/crate/crate-alerts/issues/227
public benchmark failed again with 85% - will increase to 90% which passes locally - I hoped that dev machine will behave differently and smaller value would be fine but this is not the case
> increase breaker limit for the public benchmark

- specs/select/huge_arrays.toml
Resolves https://github.com/crate/crate-alerts/issues/228
tested locally, got error without this change and worked with it
> autogenerate data for huge_arrays on setup

- specs/select/hash_joins.toml
- tracks/default.toml
Resolves https://github.com/crate/crate-alerts/issues/229
run  
`cr8 run-crate ./ -e CRATE_HEAP_SIZE=4g \
--s indices.breaker.query.limit=80% -- run-spec  ../crate-benchmarks/specs/select/hash_joins.toml {node.http_url}`
thrice on a local spec with concurrency 17 and it didn't fail
> reduce query circuit breaker back to 80% and set lower concurrency 

- compare_run.py
- specs/insert_bulk.toml
- Extend insert_bulk benchmarks
- Run `load_data` action in compare_run
> Extend insert benchmarks

- specs/array_length.toml
Used to measure https://github.com/crate/crate/pull/12696
> Add `xs = []` case to array_length benchmark

- query_tests/generate_rnd_queries.py
Follow up to https://github.com/crate/crate-benchmarks/commit/8a6066d36eafa0b7ad79ad75450fd584e3d3537c
Job failed on Jenkins:
Traceback (most recent call last):
File "/var/lib/jenkins/workspace/CrateDB/nightly/rnd_query_tests/venv/lib/python3.8/site-packages/cr8/run_track.py", line 39, in _run_specs
do_run_spec(
File "/var/lib/jenkins/workspace/CrateDB/nightly/rnd_query_tests/venv/lib/python3.8/site-packages/cr8/run_spec.py", line 257, in do_run_spec
executor.run_queries(spec.queries, spec.meta)
File "/var/lib/jenkins/workspace/CrateDB/nightly/rnd_query_tests/venv/lib/python3.8/site-packages/cr8/run_spec.py", line 180, in run_queries
for query in queries:
File "/var/lib/jenkins/workspace/CrateDB/nightly/rnd_query_tests/query_tests/generate_rnd_queries.py", line 503, in queries_for_spec …
> Fix `provider_for_column` calls in rnd-query generation

- .taplo.toml
If using https://taplo.tamasfe.dev/ this allows to get completion for
spec file properties and schema validation/error reporting
(needs taplo version 0.7.2, there was a bug in 0.7.0 that prevented the config from working)
> Add taplo config to set cr8 spec file schema

- long_running/queries.py
`SqlException: SQLParseException[line 1:94: mismatched input 'lrt' expecting {<EOF>, ';'}] occurred using: {"stmt": "SELECT lrt.t1.dev, lrt.t2.name FROM lrt.t1 INNER JOIN lrt.t2 ON lrt.t1.dev = lrt.t2.devWHERE lrt.t1.dev = CAST(random() * 127 AS BYTE) ORDER BY lrt.t2.name LIMIT 100"}`
This issue ^ [pops up from time to time](https://github.com/crate/crate-alerts/search?q=%22lrt.t1.dev+%3D+lrt.t2.devWHERE%22&type=issues) and gets automatically closed.
> Add whitespace before WHERE clause

- long_running/queries.py
https://jenkins.crate.io/job/CrateDB/job/nightly/job/long_running/
1. one of the queries was never executed, crate-alerts issue used to [pop up and then be autofixed](https://github.com/crate/crate-alerts/search?q=%22lrt.t1.dev+%3D+lrt.t2.devWHERE%22&type=issues) on the next day.
2. we recently fixed the query in https://github.com/crate/crate-benchmarks/commit/766046138ffb6bb788d3e03bfe4707267dc92b02 and now we have failures like
`JobKilledException[Job killed. Received data for job=a0750cfc-5af0-79da-d020-6999047c3699 but there is no job   context present. This can happen due to bad network latency or if individual nodes are unresponsive due to high load] occurred using: {"stmt": "SELECT lrt.t1.dev, lrt.t2.name FROM lrt.t1 INNER JOIN lrt.t2 ON lrt.t1.dev = lrt.t2.dev WHERE lrt.t1.dev = …
> lower concurrency for long-running query as it causes JobKilledException

- long_running/queries.py
follow up to https://github.com/crate/crate-benchmarks/commit/2979d0721d8e613ddbd47020377fc0de9f898c22 as JobKilledException error still pops up
Note, that this is not a regression as this query was never executed before due to syntax error.
> lower concurrency for long-running query

- tracks/latest.toml
Follow up of https://github.com/crate/crate-benchmarks/commit/93913f6.
> Include correlated_suubqueries spec in the default run

- specs/select/correlated_subqueries.toml
Follow up to https://github.com/crate/crate-benchmarks/commit/93913f600338ba3a9a1a52776555ede66177f539
In order to align with https://github.com/crate/crate-benchmarks/commit/ddab6d42f6927a7bfa42a0b6312ecb54a6b3e053, which we did to address `RelationUnknown` errors
see https://jenkins.crate.io/job/CrateDB/job/nightly/job/crate-dev-cluster-bench/361/console
>  cr8 run-spec /var/lib/jenkins/workspace/CrateDB/nightly/crate-dev-cluster-bench/specs/select/correlated_subqueries.toml 'hosts' --action teardown
> SqlException: RelationUnknown[Relation 'uservisits' unknown] occurred using: {"stmt": "drop table uservisits"}
> Add 'if exists' to correlated subqueries teardown

- long_running/queries.py
lower concurrency for long-running query (third time) and slightly reduce duration
follow up to https://github.com/crate/crate-benchmarks/commit/5c19435371d20c61b7ce1236d818c76e9ba88101 as JobKilledException error still pops up
this is a heavy query (with unavoidable fullscan because of random in where) which was never executed before, so we have to keep tuning concurrency/duration util we get it working.
> lower concurrency for long-running query (third time) and slightly reduce duration

- specs/select/sys_shards.toml
Follow up to https://github.com/crate/crate-benchmarks/commit/ddab6d42f6927a7bfa42a0b6312ecb54a6b3e053
https://jenkins.crate.io/job/CrateDB/job/nightly/job/crate-dev-cluster-bench/376/console
`SqlException: RelationUnknown[Relation 'blob.b_t_shards' unknown] occurred using: {"stmt": "drop blob table b_t_shards"}`
> Add 'if exists' to blob table

- tracks/latest.toml
The right path is `../specs/select/sys_shards` which is also in the list.
> Remove missing sys_shards.toml from latest track

- long_running/queries.py
The query gets stuck and causes the test to fail.
This removes it until we have a fix in place
Created https://github.com/crate/crate/issues/14111 to track it.
> Remove group by query from long_running

- specs/select/sys_select.toml
The large number of iterations doesn't necessary lead to more stable
results.
E.g. comparing `latest-nightly` with `latest-nightly` leads to results
like:
Q: select name from sys.cluster
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        0.053 ±    0.045 |      0.017 |      0.035 |      0.054 |      0.431 |
|   V2    |        0.053 ±    0.049 |      0.018 |      0.036 |      0.055 |      0.405 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   1.64%                           +   4.02%
Or:
Q: select * from sys.jobs
C: 1
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        0.054 ±    0.040 |      0.026 | …
> Reduce iterations in sys_select.toml

- join-order-benchmark/job.toml
Most of these queries are currently really slow.
Reduce iterations until we've a couple of results and a better overview
of which are fast enough to turn the number of iterations up
> Reduce iterations in join-order-benchmark

- requirements.txt
``cr8 0.25.0`` adds compatibility for ``argh>=0.30.1``
This reverts commit cb82b8f11ecc5dffe724d29b4e396f4ff4a1707b.
> Revert "Pin argh dependency to 0.29.4"

- jfr_profiles/disk_profile.jfc
Example use:
```bash
#!/usr/bin/env bash
set -Eeuo pipefail
pid=$("$JAVA_HOME/bin/jps" | awk '/CrateDB/ { print $1 }')
version=$(crash --hosts localhost:4200 -c "select version['build_hash'] as hash from sys.nodes" --format json | jq -r '.[0] | .hash')
crash --hosts localhost:4200 -c "set global stats.service.max_bytes_per_sec = '5mb'"
echo 3 | sudo tee /proc/sys/vm/drop_caches
jcmd "$pid" JFR.start \
name=recording \
duration=1m \
filename="$(pwd)/profile.jfr" \
settings="$(pwd)/jfr_profiles/disk_profile.jfc"
crash --hosts localhost:4200 -c "analyze"
jcmd "$pid" JFR.stop name=recording
"$JDK21/bin/jfr" view file-reads-by-path profile.jfr > "version-$version.txt"
```
> Add JFR profile that samples FileRead/Write events with 0 ns threshold

- specs/select/correlated_subqueries.toml
As can be seen from 
https://tools.cr8.net/grafana/d/-8PNA2vnz/cratedb-dev-cluster-benchmarks?orgId=1&var-spec_file=correlated_subqueries.toml&var-statement=SELECT%20COUNT%28%2A%29%20FROM%20uservisits%20u%20WHERE%20%22lCode%22%20LIKE%20%27%25-EN%27%20AND%20EXISTS%20%28SELECT%201%20FROM%20uservisits%20WHERE%20%22cCode%22%20%3D%20u.%22cCode%22%29&var-concurrency=1&from=now-6M&to=now
the benchmark results on dev cluster fluctuates as much as 1 minute when it typically runs for 3-4 minutes.
> Reduce fluctuation of correlated-subquery

- specs/udf.toml
Just used this to test if it is feasible to remove the `compile` variant of the udf-scalar implementation. (It's not).
But might as well add the file.
> Add spec file for UDF

- tracks/latest.toml
It's not part of the latest.toml
This reverts commit c3817c1653724dae1ca37a82c49aa6ae15993436.
> Revert "Add group by distribution to the full run"

- specs/lookup_join.toml
Depending on https://github.com/mfussenegger/cr8/pull/381
> Enable lookup-joins for join benchmarks based on session settings

- compare_run_disk_usage.py
- requirements-raw.txt
`compare_run_disk_usage.py` was broken because the tabulate import from crash was broken. This declares the dependency explicitly and makes the script work again.
Related to https://github.com/crate/crash/commit/2a0ea945ddc8519cc066550bd66527ce284e1757
> Make compare_run_disk_usage working again

- compare_run_disk_usage.py
- lucene_disk_usage.py
This fixes the size calculation for numerical data in lucene indices and adds a total row to the results. The new output for `compare_run_disk_usage` looks like this:
```
Description             Version 1  Unit      Version 2  Unit      Diff
--------------------  -----------  ------  -----------  ------  ------
Segment Info                 8.99  KB             8.99  KB        0.00
Fields                       7.44  KB             7.35  KB        1.32
Field Index                 39.21  KB            13.24  KB       99.05
Field Data                 409.80  MB            89.69  MB      128.18
Term Dictionary            155.97  MB           155.97  MB        0.00
Term Index                   1.27  MB             1.27  MB        0.01
Frequencies                 48.64  MB            48.58  MB …
```
> Fix size calculation for numerical data

- tracks/latest.toml
We use track file to run benchmarks and setup from the spec specified in fixtures is called once
standalone run-spec works but to make run-track work we need to use fixture that creates all tables required in other benchmarks
Fixes https://github.com/crate/crate-alerts/issues/708
> Use aggregate.toml as a base for fixtures.

- specs/select/hash_joins.toml
crate-public-benchmark started to fail and is blocking the nightly releases, see https://github.com/crate/crate-alerts/issues/739 for details. The Jenkins results can be interpreted as some sort of a regression but it could not reproduced locally(could not reproduce the good state before it started to fail, in addition there were no signs of increase in memory consumptions of the hash join operations).
> Reduce concurrency to prevent CBE

- specs/overload_read.py
Can be used to get a node into a state where `crash` connecting takes a long time, and overall responsiveness degrades a lot.
Related to https://github.com/crate/crate/issues/17646
> Add spec file that overloads a tiny node

- specs/select/hash_joins.toml
The scenario currently runs often into circuit breaker exceptions.
This removes it until we have a solution for that in CrateDB to avoid
notiification noise and interferring with other benchmarks.
(Possible solution being spilling to disk:
https://github.com/crate/crate/issues/17431 - added a note to it to undo this PR)
> Remove hash join case with concurrency=17

- specs/select/hash_joins.toml
The scenario currently runs often into circuit breaker exceptions. This removes it until we have a solution for that in CrateDB to avoid notiification noise and interferring with other benchmarks.
(Possible solution being spilling to disk:
https://github.com/crate/crate/issues/17431)
> Remove hash join case with concurrency=14
