crate/crate-benchmarks

rerun-bench.sh
=> improve multi-line tarball list in benchmark-rerun

src/test/java/io/crate/consumer/CrateConsumer.java
=> make gson an object variable to redurce

src/test/java/io/crate/stress/AbstractIntegrationStressTest.java
in order that es-client is removed because of backwards compaitibility
(elasticsearch 2.0 upgrade) the ensure green and yellow states have been
rewritten.
=> rewrite ensure green and yellow state

py/specs/in_numeric.toml, py/tracks/latest.toml
@kovrus can you take a look please!
=> added "IN numeric" benchmark

py/specs/delete_bulk.py, py/specs/delete_single.py, py/tracks/latest.toml
* `specs/delete_single.py`
* `specs/delete_bulk.py`
requires https://github.com/mfussenegger/cr8/pull/93 for args/bulk_args generation
=> Added delete benchmarks

py/specs/create_partitions.py
has the same requirement as https://github.com/crate/crate-stresstest/pull/55
=> add iterations to the create partitions benchmark

py/specs/count.toml, py/specs/group_by.toml, py/specs/in_numeric.toml, py/specs/in_string.toml, py/specs/like.toml, py/specs/queries.toml, py/specs/select.toml
=> Introduced narrower wildcard to 'copy uservisits from' query in benchmarks

api/README.rst
@m-kharbat can you take a look please
=> fixed typo in api readme

py/specs/sql/uservisits.sql
=> disable refresh during copy from

py/gen_rerun_config.py
to re-run specs on all nightlies
@m-kharbat @mikethebeer please
=> added script that generates a config.toml

api/config.toml, py/specs/upsert_bulk.py, py/specs/upsert_single.py, py/tracks/latest.toml
so they can be displayed within single operations chart and bulk operations chart
=> refactored upsert benchmarks

api/config.toml
=> put generated columns benchmark into separate group

api/src/crate/benchapi/application.py
=> fixed broken strptime import

api/config.toml, py/tracks/latest.toml
https://github.com/crate/crate-web/pull/462
=> added outer joins to benchmark track

api/src/crate/benchapi/application.py
this is necessary to be able to display hash and date at x-axis
also added additional ordering by build_version
@bogensberger please
=> added version_info column to api response

py/specs/group_by.toml, py/specs/in_numeric.toml, py/specs/in_string.toml, py/specs/select.toml, py/tracks/latest.toml
Requires https://github.com/mfussenegger/cr8/pull/117
=> Change track file to use shared setup

py/tracks/default.toml
new jenkins slaves have less memory available
https://jenkins.crate.io/job/cratedb/job/nightly/job/crate-public-bench/32/console
=> reduced heap size for new jenkins slaves

py/specs/union.toml, py/tracks/latest.toml
=> Add stresstest for Union All

py/find_regressions.py
This adds meta_name and bulk_size to the key used to group benchmarks.
Previously it incorrectly compared different benchmarks with each
other, leading to reports with high differences.
(E.g. comparing a benchmark with bulk_size=1000, with a benchmark with
bulk_size=1)
(There seems to be a separate issue in either cr8, or the script
saving the benchmark results into the benchmark table that causes
`bulk_size` to always be NULL)
=> Avoid false positive reports from find_regressions

py/find_regressions.py
This changes the script so that known unstable tests no longer cause a
exit code of 1 (to not fail a jenkins job run).
=> Extend find_regressions to filter known unstable tests

query_tests/generate_rnd_queries.py
- Use `IS NULL` sometimes
- Randomly use `distance` or `within` if applicable
=> Extend random query generation

query_tests/generate_rnd_queries.py
=> Fix a couple of scalars where we didn't generate the correct expressions.

query_tests/generate_rnd_queries.py
duration parameter was missing.
=> Fix random query spec file

specs/select/count.toml, specs/select/hyperloglog.toml, tracks/latest.toml
also adds a count distinct benchmarks and moves the count benchmarks into the `select/` folder
=> adds hyperloglog benchmarks

query_tests/generate_rnd_queries.py
In order to test functions against different value types (byte, long, etc)
we get to value 1 and keep the type by using arithmetic operations on the
column.
=> Some functions need non-zero positive values (eg log).

specs/upsert_bulk.py
Followup of 605b959c9f24a2a8691b2b025c46ae15751133e8
=> Fix filename and typo for bulk upserts.

compare.py
New output format:
Q: select 1
C: 25
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |        3.283 ±   13.208 |      0.245 |      0.970 |      1.734 |    118.150 |
|   V2    |        3.942 ±   18.727 |      0.245 |      0.797 |      1.190 |    132.277 |
mean:   +  18.24%
median: -  19.58%
Likely NOT significant
=> compare: Print results per fork and re-format output

find_regressions.py, line_regress.py
Should help in filtering out some false positives
=> Consider linregress slope for performance regression detection

requirements.txt
https://nvd.nist.gov/vuln/detail/CVE-2018-19352
https://nvd.nist.gov/vuln/detail/CVE-2018-19351
=> Bump notebook version to 5.7.2

compare_run.py
To be able to compare the same version with different settings.
Useful if you want to see the effect of a different heap setting or
different GC settings.
=> Extend compare_run to allow different env/settings per version

specs/upsert_bulk.py, specs/upsert_single.py
Support for ON DUPLICATE KEY syntax was removed on crate master.
=> Change queries from `on duplicate key` to `on conflict`

requirements.txt
=> Update urllib3 to handle a known security issue

query_tests/generate_rnd_queries.py
=> Use window functions in the select list.

README.rst, specs/like.toml
=> Add benchmark for the ilike operator, to compare it with like

specs/distinct_limit.toml
Related to https://github.com/crate/crate/pull/9371
=> Add spec file for select distinct with limit

query_tests/generate_rnd_queries.py
=> Fetch rnd-query tests data set from CDN

compare_measures.py, specs/insert_select_distinct.toml
Relates to https://github.com/crate/crate/issues/10082
=> Add spec file for insert from select distinct case

jfr.sh
Had this lying around in my workspace for quite some time. I guess it doesn't hurt to check it in.
=> Add a script to profile a running instance

compare_run_disk_usage.py, lucene_disk_usage.py
These changes make it easier to use the script in a job that stores the
results into a CrateDB cluster.
=> Exclude dot from fileext; Allow to write result to file

compare_run_disk_usage.py
The version 2 column displayed the v1 value again
=> Fix disk usage comparison table

compare_run.py
=> Handle `java_home == None` case in compare_run script

compare_measures.py, compare_run.py, requirements-raw.txt, requirements.txt
An example:
```
Q: select count(distinct "searchWord") from uservisits group by "cCode"
C: 5
| Version |         Mean ±    Stdev |        Min |     Median |         Q3 |        Max |
|   V1    |     1031.266 ±  256.775 |    851.142 |    974.662 |   1031.601 |   2181.788 |
|   V2    |     1085.324 ±  238.921 |    889.406 |   1035.585 |   1096.948 |   2172.956 |
├---------┴-------------------------┴------------┴------------┴------------┴------------┘
|               +   5.11%                           +   6.06%
There is a 87.51% probability that the observed difference is not random, and the best estimate of that difference is 5.11%
The test has no statistical significance
┌───────────────────────────────────────────────────────────────────────────────────────────────┐
2181.8┤ ▖▖▖ v1 …
```
=> Add option to print plots in compare_run

specs/select/wide_table.toml
Resolves https://github.com/crate/crate-alerts/issues/230
=> autogenerate data for wide table spec on setup

specs/insert_bulk.toml
~~Requires a new release of cr8 with https://github.com/mfussenegger/cr8/pull/353~~ (released cr8 0.22.0)
=> Add uservisits to insert_bulk spec

specs/select/is-null.toml
See
- https://github.com/crate/crate/pull/13771
- https://github.com/crate/crate/issues/13769
=> Add a spec to benchmark `IS NOT NULL` on objects

long_running/queries.py
Pre-requisite for https://github.com/crate/jenkins-dsl/pull/1128
Similar to https://github.com/crate/crate-benchmarks/pull/238
=> Add 'if exists' to long-running teardown

specs/select/is-null.toml
Performance depends a lot on whether there are few matches or many
matches.
=> Add few_null variant to is-null spec

specs/lookup_join.toml
Let's move to count before we run the first nightly benchmark.
=> Change lookup join benchmark to count

tracks/latest.toml
Follow-up https://github.com/crate/crate-benchmarks/pull/302
=> Add lookup join benchmark to full run

specs/lookup_join.toml
=> Add optimize to lookup join benchmark 

requirements.txt
https://github.com/mfussenegger/cr8/commit/a053e80bc43dd5e584b14529f54dcacca22207a3
=> Bump cr8 to 0.26.0

requirements.txt
This reverts commit 8b86c8808853dbfe0c41b971d03a3d10a66799b9.
=> Revert "Bump cr8 to 0.26.0"

specs/lookup_join.toml
Benchmark for https://github.com/crate/crate/pull/15840
=> Add benchmark for lookup-join with aggregation

tracks/latest.toml
Follow up to https://github.com/crate/crate-benchmarks/commit/f60803b2c3457daf52d8620b916982433634ab9f
=> Add group by distribution to the full run

specs/numeric.toml
(Currently requires a mkjson dev build to generate the data)
=> Add query benchmarks for numeric types

specs/select/topk_aggregations.toml, tracks/latest.toml
This adds benchmarks for the core usecases for topk for string/numerical values with and without doc values.
=> Add topk benchmarks

specs/sql/percentile_small.sql
Follow up to https://github.com/crate/crate-benchmarks/pull/329/commits/19ccf0fe19a11b0e8570996f31f91011c54b84cb
Fixes https://github.com/crate/crate-alerts/issues/706
=> Add definition of the percentile_small table

compare_run.py
cr8 already support using the `asyncpg` client to connect using the PG protocol.
The new `--protocol` parameter of `compare_run` can be used to switch to `asyncpg` when setting it to `pg`.
=> Add support to `compare_run` for using the PG procotol

compare_run.py
Example output:
perf stat
v1
branches             :   662304731.00
cache-misses         :    39253656.00
instructions         :           0.00
faults               :        4626.00
context-switches     :        6099.00
L1-dcache-loads      :  1415607468.00
L1-dcache-load-misses:           5.20
v2
branches             :   674325494.00
cache-misses         :    39069944.00
instructions         :           0.00
faults               :        4467.00
context-switches     :        6046.00
L1-dcache-loads      :  1453971001.00
L1-dcache-load-misses:           5.16
=> Add perf stat output to compare_run.py output
